import {
  Component,
  Input,
  ChangeDetectionStrategy,
  OnInit,
  OnChanges,
  ElementRef,
} from '@angular/core';
import { FudisHeadingLevel, FudisHeadingVariant } from '../../../types/typography';
import { FudisIdService } from '../../../services/id/id.service';
import { FudisComponentChanges } from '../../../types/miscellaneous';
import { FudisTextAlign } from '../../../types/typography';
import { BehaviorSubject } from 'rxjs';
import { getVariant } from '../../../utilities/typography/typography-utils';

@Component({
  selector: 'fudis-heading',
  templateUrl: './heading.component.html',
  styleUrls: ['./heading.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeadingComponent implements OnInit, OnChanges {
  constructor(
    private _idService: FudisIdService,
    private _headingElement: ElementRef,
  ) {
    /**
     * Set Heading wrapper to be "full width" if used inside Grid
     */
    (_headingElement.nativeElement as HTMLHeadingElement).style.gridColumn = '1/-1';
  }

  /**
   * Semantic level of heading
   */
  @Input({ required: true }) level: FudisHeadingLevel;

  /**
   * Heading variant
   */
  @Input() variant: FudisHeadingVariant;

  /**
   * Heading id. If not provided, generated by FudisIdService.
   */
  @Input() id: string;

  /**
   * Align heading
   */
  @Input() align: FudisTextAlign = 'left';

  /**
   * Heading CSS class list
   */
  protected _classList = new BehaviorSubject<string[]>([]);

  /**
   * Internal id to generate unique id
   */
  protected _id: string;

  /**
   * Set CSS classes for heading
   */
  private _setClasses(): void {
    const calcVariant = this.variant || getVariant(this.level);

    const newClasses = [
      `fudis-heading`,
      `fudis-heading__variant__${calcVariant}`,
      `fudis-heading__align__${this.align}`,
    ];

    this._classList.next(newClasses);
  }

  ngOnInit(): void {
    this._id = this.id ?? this._idService.getNewId('heading');

    this._setClasses();
  }

  ngOnChanges(changes: FudisComponentChanges<HeadingComponent>): void {
    if (
      changes.align?.currentValue !== changes.align?.previousValue ||
      changes.variant?.currentValue !== changes.variant?.previousValue ||
      changes.level?.currentValue !== changes.level?.previousValue
    ) {
      this._setClasses();
    }
  }
}
