# Following Fudis Ngx package ecosystems that are updated by Dependabot. Excluding all major package updates handled by a developer.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      linting:
        applies-to: version-updates
        patterns:
          - "prettier"

  - package-ecosystem: npm
    directory: "/ngx-fudis"
    schedule:
      interval: daily
    allow:
      - dependency-name: "@angular*"
    security-updates-only: true
    groups:
      angular-security:
        patterns:
          - "@angular*"

  - package-ecosystem: npm
    directory: "/ngx-fudis"
    schedule:
      interval: weekly
    groups:
      angular-version:
        applies-to: version-updates
        patterns:
          - "@angular*"
          
      storybook:
        applies-to: version-updates
        patterns:
          - "@storybook*"

      linting:
        applies-to: version-updates
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
          - "stylelint*"

      testing:
        applies-to: version-updates
        patterns:
          - "jest*"

      babel:
        applies-to: version-updates
        patterns:
          - "@babel*"
          - "babel-loader"

      typescript:
        applies-to: version-updates
        patterns:
          - "typescript"
          - "ts-node"
      others:
        applies-to: version-updates
        patterns:
          - "*"

      angular:
        applies-to: security-updates
        patterns:
          - "@angular*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: "/ngx-fudis/projects/ngx-fudis"
    schedule:
      interval: daily
    allow:
      - dependency-name: "@angular*"
    security-updates-only: true
    groups:
      angular-security:
        patterns:
          - "@angular*"

  - package-ecosystem: npm
    directory: "/ngx-fudis/projects/ngx-fudis"
    schedule:
      interval: weekly
    groups:
      angular-version:
        applies-to: version-updates
        patterns:
          - "@angular*"
      typescript:
        applies-to: version-updates
        patterns:
          - "tslib"
          - "typescript"
      others:
        applies-to: version-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: "/test"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]


  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/ngx-fudis"
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: "/test"
    schedule:
      interval: weekly
