import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';
import { NgxFudisModule } from '../../../../ngx-fudis.module';
import { FudisSelectOption } from '../../../../types/forms';
import { defaultOptions } from '../common/mock_data';

/**
 * This code is mainly generated by Copilot. It is supposed to be just an example case of how to
 * sync selection between two independent MultiselectComponents that share some options but also
 * have their own unique options.
 */

@Component({
  imports: [NgxFudisModule],
  selector: 'example-multiselect-showcase-no-form',
  template: `
    <fudis-heading [level]="2"
      >Multiselects with independent controls but synced selection</fudis-heading
    >
    <fudis-body-text class="fudis-mb-md"
      >Both Multiselects have their own options but also one shared option. Selecting this shared
      option should reflect on both of the Multiselects' FormControls. Clearing all selected options
      should also clear the shared option from the other Multiselect.</fudis-body-text
    >
    <div style="display: flex; gap: 2rem;">
      <div style="flex: 1;">
        <fudis-multiselect
          [size]="'lg'"
          [variant]="'dropdown'"
          [placeholder]="'Choose a pet (1)'"
          [control]="control1"
          [label]="'Select a pet (1)'"
          [selectionClearButton]="true"
          (selectionUpdate)="onSelectionUpdate(1, $event)"
        >
          <ng-template fudisSelectOptions>
            @for (option of options1; track option.value) {
              <fudis-multiselect-option [data]="option"></fudis-multiselect-option>
            }
          </ng-template>
        </fudis-multiselect>
      </div>
      <div style="flex: 1;">
        <fudis-multiselect
          [size]="'lg'"
          [variant]="'dropdown'"
          [placeholder]="'Choose a pet (2)'"
          [control]="control2"
          [label]="'Select a pet (2)'"
          [selectionClearButton]="true"
          (selectionUpdate)="onSelectionUpdate(2, $event)"
        >
          <ng-template fudisSelectOptions>
            @for (option of options2; track option.value) {
              <fudis-multiselect-option [data]="option"></fudis-multiselect-option>
            }
          </ng-template>
        </fudis-multiselect>
      </div>
    </div>
    <fudis-heading [level]="3" class="fudis-mt-md">Selected options:</fudis-heading>
    @for (opt of sharedSelectedOptions; track opt.value) {
      <fudis-body-text>{{ opt.label }} ({{ printControlValue(opt.value) }})</fudis-body-text>
    }
  `,
})
export class StorybookExampleMultiselectShowcaseNoFormComponent {
  // options1 and options2 have some overlap, some unique
  options1: FudisSelectOption<string | object>[] = [
    defaultOptions[0],
    defaultOptions[1],
    defaultOptions[2],
  ];
  options2: FudisSelectOption<string | object>[] = [
    defaultOptions[1],
    defaultOptions[3],
    defaultOptions[5],
    defaultOptions[7],
  ];

  control1 = new FormControl<FudisSelectOption<string | object>[] | null>([]);
  control2 = new FormControl<FudisSelectOption<string | object>[] | null>([]);

  sharedSelectedOptions: FudisSelectOption<string | object>[] = [];

  // Called when either multiselect changes
  onSelectionUpdate(source: 1 | 2, newSelection: FudisSelectOption<string | object>[] | null) {
    // Get the other control and its value
    const thisControl = source === 1 ? this.control1 : this.control2;
    const otherControl = source === 1 ? this.control2 : this.control1;
    const otherOptions = source === 1 ? this.options2 : this.options1;
    const prevValue = thisControl.value || [];
    const otherPrevValue = otherControl.value || [];

    // If selection is cleared, recalculate sharedSelectedOptions from both controls
    if (newSelection === null) {
      // Determine which control was cleared
      const clearedControl = source === 1 ? 'control1' : 'control2';
      const otherControlRef = source === 1 ? this.control2 : this.control1;
      const otherOptionsRef = source === 1 ? this.options2 : this.options1;
      const clearedOptions = source === 1 ? this.options1 : this.options2;

      // Set the cleared control to empty
      this[clearedControl] = new FormControl<FudisSelectOption<string | object>[]>([]);

      // Find shared options (present in both selects)
      const sharedOptionValues = clearedOptions
        .filter((opt) => otherOptionsRef.some((o) => o.value === opt.value))
        .map((opt) => opt.value);
      const filteredOther = (otherControlRef.value || []).filter(
        (opt) => !sharedOptionValues.includes(opt.value),
      );
      if (source === 1) {
        this.control2 = new FormControl<FudisSelectOption<string | object>[]>(filteredOther);
      } else {
        this.control1 = new FormControl<FudisSelectOption<string | object>[]>(filteredOther);
      }

      // Update sharedSelectedOptions
      const values1 = this.control1.value || [];
      const values2 = this.control2.value || [];
      const combined = [...values1, ...values2];
      const shared = combined.filter(
        (opt, idx, arr) => arr.findIndex((o) => o.value === opt.value) === idx,
      );
      this.sharedSelectedOptions = shared;
      return;
    }

    // Detect removed options (chip or dropdown unselect)
    const newValues = (newSelection || []).map((opt) => opt.value);
    const removed = prevValue.filter((opt) => !newValues.includes(opt.value));

    // If a removed option is shared, remove it from the other control as well
    let updatedOther = otherPrevValue;
    let removedShared = false;
    for (const opt of removed) {
      // Is it a shared option?
      if (otherOptions.some((o) => o.value === opt.value)) {
        updatedOther = updatedOther.filter((o) => o.value !== opt.value);
        removedShared = true;
      }
    }
    // Update the other control if needed
    if (removedShared) {
      if (source === 1) {
        this.control2 = new FormControl<FudisSelectOption<string | object>[]>(updatedOther);
      } else {
        this.control1 = new FormControl<FudisSelectOption<string | object>[]>(updatedOther);
      }
    }

    // Union of both controls' values, unique by value
    const combined = [...(newSelection || []), ...updatedOther];
    const shared = combined.filter(
      (opt, idx, arr) => arr.findIndex((o) => o.value === opt.value) === idx,
    );
    this.sharedSelectedOptions = shared;

    // For each control, filter sharedSelectedOptions to only those present in its options
    const new1 = this.options1.filter((opt) =>
      this.sharedSelectedOptions.some((sel) => sel.value === opt.value),
    );
    const new2 = this.options2.filter((opt) =>
      this.sharedSelectedOptions.some((sel) => sel.value === opt.value),
    );

    // Only update if value actually changed to avoid infinite loops
    const isEqual = (
      a: FudisSelectOption<string | object>[],
      b: FudisSelectOption<string | object>[],
    ) => a.length === b.length && a.every((v, i) => v.value === b[i].value);

    if (!isEqual(this.control1.value || [], new1)) {
      this.control1 = new FormControl<FudisSelectOption<string | object>[]>(new1);
    }
    if (!isEqual(this.control2.value || [], new2)) {
      this.control2 = new FormControl<FudisSelectOption<string | object>[]>(new2);
    }
  }

  printControlValue(value: object | string) {
    return typeof value === 'object' ? JSON.stringify(value) : value;
  }
}
