import {
  Directive,
  Input,
  EventEmitter,
  Output,
  Signal,
  effect,
  ViewChild,
  ElementRef,
  OnDestroy,
  ChangeDetectorRef,
} from '@angular/core';
import { TooltipApiDirective } from '../../tooltip/tooltip-api.directive';
import { FudisTranslationService } from '../../../services/translation/translation.service';
import { FudisTranslationConfig } from '../../../types/miscellaneous';
import { FudisIdComponent } from '../../../types/id';
import { FudisIdService } from '../../../services/id/id.service';
import { FormControl } from '@angular/forms';
import { Subject } from 'rxjs';

@Directive({
  selector: '[fudisInputBase]',
})
export class InputBaseDirective extends TooltipApiDirective implements OnDestroy {
  constructor(
    protected _translationService: FudisTranslationService,
    protected _idService: FudisIdService,
    protected _changeDetectorRef: ChangeDetectorRef,
  ) {
    super();

    effect(() => {
      this._translations = _translationService.getTranslations();
      this._requiredText = this._translations().REQUIRED;
      _changeDetectorRef.detectChanges();
    });
  }

  /**
   * Template reference for input. Used in e. g. initialFocus
   */
  @ViewChild('inputRef') protected _inputRef: ElementRef<HTMLInputElement>;

  /**
   * Label for the input.
   */
  @Input({ required: true }) label: string;

  /**
   * Provide additional information for screen reader users by extending text content of the label. Used in e. g. input with language options for providing info about currently selected language.
   */
  @Input() ariaLabel: string;

  /**
   * Input id. If not provided, generated by Id Service
   */
  @Input() id: string;

  /**
   * If component is a child of Form component, Form's Error Summary is visible, this component's control has errors and when this component is loaded for the first time, it will by default call Error Summary to reload itself again and mark control as touched. This is because if component is lazy loaded to the DOM after the initial reload errors call was made, errors of this component might not appear on the list. To disable this feature, set this to false.
   */
  @Input() errorSummaryReloadOnInit: boolean = true;

  // TODO: Disabling should be done straight from the form control. But because form control sets HTML disabled="true" and not only aria-disabled="true", this will be prevent user to focus on input even if it 'disabled'. As long this Angular 'feature' exists, we should 'manually' provide disabling through input as well.

  /**
   * Option for disabling the input.
   */
  @Input() disabled: boolean = false;

  /**
   * Help text, aligned underneath the input.
   */
  @Input() helpText: string | undefined;

  /**
   * Set input's visual style and attributes as invalid. Does not override if control.invalid is true.
   */
  @Input() invalidState: boolean = false;

  /**
   * Set browser focus to the input on the first load.
   */
  @Input() initialFocus: boolean = false;

  /**
   * Disable guidance for this component instance. No help text or errors will be visible.
   */
  @Input() disableGuidance: boolean;

  /**
   * To listen for input's blur event.
   */
  @Output() handleBlur: EventEmitter<FocusEvent> = new EventEmitter<FocusEvent>();

  /**
   * To listen for input's key up event.
   */
  @Output() handleKeyUp: EventEmitter<KeyboardEvent> = new EventEmitter<KeyboardEvent>();

  /**
   * Basic Fudis translation keys
   */
  protected _translations: Signal<FudisTranslationConfig>;

  /**
   * Fudis translation key for required text
   */
  protected _requiredText: string;

  /**
   * Set requiredText based on this boolean value
   */
  protected _required: boolean = false;

  protected _destroyed = new Subject<void>();

  /**
   * To trigger Error Summary reload when this component's children Validator Error Messages are initialised. This is used in cases when this component is lazy loaded to DOM after initial Error Summary reload was called before children Validator Error Messages existed. E. g. if component is inside lazy loaded expandable.
   */
  protected _reloadErrorSummary = false;

  /**
   * TODO: write test
   *
   * Tell Guidance, that this component has errors which were not loaded to Error Summary, if component was initialised after parent's Error Summary was set to visible.
   */
  protected _reloadErrorSummaryOnInit(
    parentFormErrorSummaryVisible: boolean | undefined,
    control: FormControl,
  ): void {
    if (this.errorSummaryReloadOnInit && parentFormErrorSummaryVisible && control.errors) {
      this._reloadErrorSummary = true;
      this._changeDetectorRef.detectChanges();
    }
  }

  /**
   * Handle blur event
   */
  public onBlur(event: FocusEvent): void {
    this.handleBlur.emit(event);
  }

  /**
   * Set focust to the input element
   */
  public focusToInput(): void {
    if (this._inputRef?.nativeElement) {
      this._inputRef.nativeElement.focus();
    }
  }

  /**
   * Add given id to Id Service or generate unique id
   */
  protected _setInputId(componentType: FudisIdComponent): void {
    if (this.id) {
      this._idService.addNewId(componentType, this.id);
    } else {
      this.id = this._idService.getNewId(componentType);
    }
  }

  ngOnDestroy(): void {
    this._destroyed.next();
  }
}
