# WIP
# Should be merged with other Storybook workflows once ready.
name: Publish Storybook by version

on:
  release:
    types: [published]

jobs:
  publish:
    name: Build and deploy Storybook
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: ngx-fudis
      - name: Build Storybook
        run: npm run build-storybook
        working-directory: ngx-fudis
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ngx-fudis/static
          destination_dir: ${{ github.ref_name }}
